set nu
set autoindent
set sts=2
set ts=4
set sw=2
set noexpandtab
set noswapfile

set wrapscan
set ch=2
set vb
set hidden
set laststatus=2
set history=300
set hlsearch
set incsearch
set autoread

syntax on

au FileType ruby setl ts=2 sts=2 sw=2 expandtab
au FileType python setl ts=4 sts=4 sw=4 expandtab
au FileType php setl ts=4 sts=4 sw=4 noexpandtab


" tab navigation like firefox 
" not work in terminal
" nnoremap <C-p>      :tabprevious<CR>
" nnoremap <C-n>      :tabnext<CR>
" nnoremap <C-t>      :tabnew<CR>
" nnoremap <C-w>      :tabclose<CR>
" inoremap <C-p>      <Esc>:tabprevious<CR>
" inoremap <C-n>      <Esc>:tabnext<CR>
" inoremap <C-t>      <Esc>:tabnew<CR>
" inoremap <C-w>      <Esc>:tabclose<CR>

" always open in tabs
nmap <leader>e :tabedit<CR>


" ++++++++++++++++++++ Vundle staff +++++++++++++++++++++
set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'tpope/vim-fugitive'
" plugin from http://vim-scripts.org/vim/scripts.html
Plugin 'L9'
" Git plugin not hosted on GitHub
Plugin 'git://git.wincent.com/command-t.git'
" git repos on your local machine (i.e. when working on your own plugin)
" Plugin 'file:///home/gmarik/path/to/plugin'
" The sparkup vim script is in a subdirectory of this repo called vim.
" Pass the path to set the runtimepath properly.
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
" Install L9 and avoid a Naming conflict if you've already installed a
" different version somewhere else.
" Plugin 'ascenator/L9', {'name': 'newL9'}
Plugin 'chr4/nginx.vim'
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

