set nu
set autoindent
set sts=4
set ts=4
set sw=4
set expandtab
set noswapfile

set wrapscan
set ch=2
set vb
set hidden
set laststatus=2
set history=300
set hlsearch
set incsearch
set autoread

syntax on

au FileType ruby setl ts=2 sts=2 sw=2 expandtab
au FileType python setl ts=4 sts=4 sw=4 expandtab
au FileType php setl ts=4 sts=4 sw=4 noexpandtab


" tab navigation like firefox 
" not work in terminal
nnoremap <C-p>      :tabprevious<CR>
nnoremap <C-n>      :tabnext<CR>
nnoremap <C-t>      :tabnew<CR>
nnoremap <C-w>      :tabclose<CR>
inoremap <C-p>      <Esc>:tabprevious<CR>
inoremap <C-n>      <Esc>:tabnext<CR>
inoremap <C-t>      <Esc>:tabnew<CR>
inoremap <C-w>      <Esc>:tabclose<CR>

" always open in tabs
nmap <leader>e :tabedit<CR>

