set nu
set autoindent
set sts=4
set ts=4
set sw=4
set expandtab
set noswapfile

set wrapscan
set ch=2
set vb
set hidden
set laststatus=2
set history=300
set hlsearch
set incsearch
set autoread


au FileType ruby setl ts=2 sts=2 sw=2 expandtab
au FileType python setl ts=4 sts=4 sw=4 expandtab
au FileType php setl ts=4 sts=4 sw=4 noexpandtab


" tab navigation like firefox 
" not work in terminal
nnoremap <C-S-tab> :tabprevious<CR>
nnoremap <C-tab>   :tabnext<CR>
nnoremap <C-t>     :tabnew<CR>
inoremap <C-S-tab> <Esc>:tabprevious<CR>
inoremap <C-tab>   <Esc>:tabnext<CR>
inoremap <C-t>     <Esc>:tabnew<CR>

