## CUSTOM ##

## OSX
if [[ "$_OS_NAME" == "Darwin" ]] && [[ -f /usr/local/bin/brew ]]; then
     eval "$(/usr/local/bin/brew shellenv)"
fi

autoload -U +X compinit && compinit
autoload -U +X bashcompinit && bashcompinit
