## CUSTOM ##
SPACESHIP_TIME_SHOW=true

autoload bashcompinit;
bashcompinit;

## OSX
if [[ "$(uname -s)" == "Darwin" ]]; then
  export PATH="$(brew --prefix php@7.1)/bin:$PATH"
  export PATH="$(brew --prefix php@7.1)/sbin:$PATH"
fi

. ~/.bash_env
. ~/.bash_aliases
. ~/.bash_functions
