time_ms
##
## POSIX complaint shell utitly functions and envs
##
source "$HOME/.shell/functions"
source "$HOME/.shell/env"
source "$HOME/.shell/aliases"
source "$HOME/.shell/xvm"

##
## OhMyZsh
##
export ZSH="$HOME/.oh-my-zsh"
export KEEP_ZSHRC="yes"
[[ -d "$ZSH" && -f "$ZSH/oh-my-zsh.sh" ]] || sh -c "$(
    export KEEP_ZSHRC=$KEEP_ZSHRC
    curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh
)"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="powerline9k"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

ZSH_DISABLE_COMPFIX=true

# Plugins
plugins=(
    git
    pyenv
    dotenv
    sudo
    golang
    common-aliases
    pyenv
    nvm
    colored-man-pages
    systemd
    themes
    perms
    docker
    docker-compose
    kubectl
    # globalias
)

source "$ZSH/oh-my-zsh.sh"

##
## correct only spelling of commands
##
unsetopt correct_all # do not correct spelling of all arguments
setopt correct

##
## starship
##
[ -f "/usr/local/bin/starship" ] || curl -sS https://starship.rs/install.sh | sh
eval "$(starship init zsh)"

### custom config which should not be synced with git
[ -f "$HOME/.zshrc_local" ] && source "$HOME/.zshrc_local"

##
## custom completions
##

if [ -n "$HOMEBREW_PREFIX" ]; then
    fpath=("$HOMEBREW_PREFIX/share/zsh-completions" $fpath)
    fpath=("$HOMEBREW_PREFIX/share/zsh/site-functions" $fpath)
    fpath=("$HOMEBREW_PREFIX/completions" $fpath)
fi

ZSH_COMPLETION_DIR="$HOME/.zsh_completion.d"
[ ! -d $ZSH_COMPLETION_DIR ] && mkdir -p "$ZSH_COMPLETION_DIR"
fpath=("$ZSH_COMPLETION_DIR" $fpath)

source "$HOME/.zsh_completion"

autoload -Uz compinit && compinit -u
autoload -Uz bashcompinit && bashcompinit

##
## PATH without duplicates
##
_dedup_path

time_ms
