dotfiles:
    - bash_functions
    - aliases_completions
    - zshrc
    - bash_aliases
    - bash_env
    - bash_profile
    - zprofile
    - bashrc
    - gitconfig
    - gitignore
    - vimrc
    - bazaar
    - tmux.conf
    - muttrc
    - config/lfm/lfm.ini
    - config/lfm/lfm.keys
    - config/lfm/lfm.theme
    - ssh/config
    - ssh/sftp-init

    - config/powerline/config.json

    - config/powerline/themes/shell/__main__.json
    - config/powerline/themes/shell/continuation.json
    - config/powerline/themes/shell/default.json
    - config/powerline/themes/shell/default_leftonly.json
    - config/powerline/themes/shell/select.json
binfiles:
    - genpassword
