dotfiles:
    - bash_functions
    - aliases_completions
    - bash_aliases
    - bash_env
    - bash_profile
    - bashrc
    - gitconfig
    - gitignore
    - vimrc
    - bazaar
    - tmux.conf
    - muttrc
    - config/lfm/lfm.ini
    - config/lfm/lfm.keys
    - config/lfm/lfm.theme
binfiles:
    - genpassword
