dotfiles:
    - bash_functions
    - aliases_completions
    - zshrc
    - bash_aliases
    - bash_env
    - bash_profile
    - zprofile
    - bashrc
    - gitconfig
    - gitignore
    - vimrc
    - bazaar
    - tmux.conf
    - muttrc
    - config/lfm/lfm.ini
    - config/lfm/lfm.keys
    - config/lfm/lfm.theme
    - ssh/config
    - ssh/sftp-init
binfiles:
    - genpassword
