dotfiles:
    - bash_functions
    - bash_aliases
    - bashrc
    - aliases_completions
    - gitconfig
    - gitignore
    - vimrc
    - bazaar
    - tmux.conf
    - profile
binfiles:
    - genpassword
