###

POST https://{{host}}/repos/{{username}}/{{$dotenv repo}}/dispatches HTTP/1.1
Accept: application/vnd.github.everest-preview+json
Content-Type: application/json
Authorization: Bearer {{$dotenv token}}


{
  "event_type": "build",
  "client_payload": {}
}

###