#!/usr/bin/env bash

set -eo pipefail

[[ $# -eq 0 ]] && {
    cat <<EOF
Usage: $0 <bundleId>

If stdin passed to the script it will convert it instead read current app (<bundleId>) settings using \`defaults\`.

EOF
    exit 1
}

if [[ ! -t 0 ]]; then
    while read -r line; do
        echo "$line" | sed '/[\{\}]/d' | sed -E 's/=//g' | sed -E "s/(.*)/defaults write ${1} \1/g"
    done
else 
    defaults read "$1" | sed '/[\{\}]/d' | sed -E 's/=//g' | sed -E "s/(.*)/defaults write ${1} \1/g"
fi
