name: build

on: repository_dispatch

jobs:
  build-on-linux:
    if: github.event.action == 'build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - name: Make stub for ./bin/task
        run: |
          cd ./bin; ln -vsf taskfile-install task; cd -
          git add --all
          cp -v ./dotfiles/gitconfig ~/.gitconfig
          git commit -a -m "Replace ./bin/task with installer"
          git tag -fa "v$(date +"%Y%m%d")"
          git push -u --tags origin ${{ github.ref }}
