name: build

on: repository_dispatch


jobs:
  build-on-linux:
    if: github.event.action == 'build'
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2
      - name: Make stub for ./bin/task
        run: |
          cd ./bin
          if [ ! -h ./bin/task ] || [ ! -f ./bin/task ]; then 
            unline ./bin/task
          fi
          ln -vsf taskfile-install task
          cd -
          git add --all
          cp -v ./dotfiles/gitconfig ~/.gitconfig
          release_name="v$(date +"%Y%m%d")"
          git commit -a -m "Release $release_name"
          git tag -f "$release_name"
          git push -f -u --tags origin ${{ github.ref }}
      - name: running tests
        run: |
          echo "dispatching tests"
          curl -i -H 'authorization: Bearer ${{ secrets.GITHUB_PAT }}' \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -H 'Content-Type: application/json' \
            -d '{"event_type": "test", "client_payload": {}}' \
            -X POST https://api.github.com/repos/${{ github.repository }}/dispatches

