name: build

on: 
  push:
    branches:
      - master

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta

      - name: Make stub for ./bin/task
        run: |
          cd ./bin; ln -vsf taskfile-install task; cd -
          git add --all
          cp -v ./dotfiles/gitconfig ~/.gitconfig
          git commit -a -m "Replace ./bin/task with installer"
          git push -u origin ${{ github.ref }}
      
      - name: Test
        run: |
          ./bin/task
          ./bin/task
          ./bin/task install


  macosx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2-beta

      - name: Make stub for ./bin/task
        run: |
          cd ./bin; ln -vsf taskfile-install task; cd -
          git add --all
          cp -v ./dotfiles/gitconfig ~/.gitconfig
          git commit -a -m "Replace ./bin/task with installer"
          git push -u origin ${{ github.ref }}
      
      - name: Test
        run: |
          ./bin/task
          ./bin/task
          ./bin/task install

