name: build

on: [push, pull_request]

jobs:
  build-on-linux:
    if: github.event.action == 'build' || github.event.action == 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Make stub for ./bin/task
        run: |
          cd ./bin; ln -vsf taskfile-install task; cd -
          git add --all
          cp -v ./dotfiles/gitconfig ~/.gitconfig
          git commit -a -m "Replace ./bin/task with installer"
          git tag -f "v$(date +"%Y%m%d")"
          git push -f -u --tags origin ${{ github.ref }}
  
  linux:
    if: github.event.action == 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: |
          ./bin/task
          ./bin/task
          ./bin/task binfiles
          ./bin/task dotfiles


  macosx:
    if: github.event.action == 'test'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: update $PATH
        run: |
          brew install coreutils
          export PATH="/usr/local/bin/:$PATH"
      - name: Test
        run: |
          ./bin/task
          ./bin/task
          ./bin/task binfiles
          ./bin/task dotfiles