name: test

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: |
          sudo ./bin/taskfile-install
          task
          task binfiles
          task dotfiles

  macosx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: installing coreutils and updating $PATH
        run: |
          brew install coreutils
          export PATH="/usr/local/bin/:$PATH"
      - name: Tests
        run: |
          ./bin/taskfile-install
          task
          task binfiles
          task dotfiles
