name: test

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: |
          make
          make all DST_BASE_DIR=/tmp
          make clean DST_BASE_DIR=/tmp

  macosx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: |
          make
          make all DST_BASE_DIR=/tmp
          make clean DST_BASE_DIR=/tmp
