name: test

on: 
  pull_request:
    paths-ignore:
      - 'bin/task'
    branches:
      - master
  push:
    paths-ignore:
      - 'bin/task'
    branches:
      - master
  
jobs:
  linux:
    if: github.event.action != 'on-build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - name: Test
        run: |
          ./bin/task
          ./bin/task
          ./bin/task binfiles
          ./bin/task dotfiles


  macosx:
    if: github.event.action != 'on-build'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2-beta
      - name: update $PATH
        run: |
          brew install coreutils
          export PATH="/usr/local/bin/:$PATH"
      - name: Test
        run: |
          ./bin/task
          ./bin/task
          ./bin/task binfiles
          ./bin/task dotfiles

