name: test

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: |
          make
          make dotfiles
          make base
          make all

  macosx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install VS Code
        run: brew install visual-studio-code
      - name: Tests
        run: |
          make
          make dotfiles
          make base
          make all
