name: test

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: |
          make
          make dotfiles DEST_DOTFILES_DIR=/tmp DEST_VSCODE_SETTINGS_DIR=/tmp
          make base DEST_DOTFILES_DIR=/tmp DEST_VSCODE_SETTINGS_DIR=/tmp
          make all DEST_DOTFILES_DIR=/tmp DEST_VSCODE_SETTINGS_DIR=/tmp

  macosx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: |
          make
          make dotfiles DEST_DOTFILES_DIR=/tmp DEST_VSCODE_SETTINGS_DIR=/tmp
          make base DEST_DOTFILES_DIR=/tmp DEST_VSCODE_SETTINGS_DIR=/tmp
          make all DEST_DOTFILES_DIR=/tmp DEST_VSCODE_SETTINGS_DIR=/tmp
