name: test

on: repository_dispatch

jobs:
  linux:
    if: github.event.action == 'test'
    runs-on: ubuntu-latest
    steps:
      - name: fetching all the repo metadata
        run: |
          git clone https://github.com/${{ github.repository }} .
          git checkout ${{ github.ref }}
      - name: Test
        run: |
          ./bin/task
          ./bin/task
          ./bin/task binfiles
          ./bin/task dotfiles

  macosx:
    if: github.event.action == 'test'
    runs-on: macos-latest
    steps:
      - name: fetching all the repo metadata
        run: |
          git clone https://github.com/${{ github.repository }} .
          git checkout ${{ github.ref }}
      - name: update $PATH
        run: |
          brew install coreutils
          export PATH="/usr/local/bin/:$PATH"
      - name: Test
        run: |
          ./bin/task
          ./bin/task
          ./bin/task binfiles
          ./bin/task dotfiles